### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by azin634** [andersinno/python-database-sanitizer#26]
Any idea why this tool can't find `mysqldump`? I can confirm that it is in my path. 

```
edwin$ database-sanitizer mysql://root@localhost/test
Traceback (most recent call last):
  File "/Users/edwin/code/test/venv/bin/database-sanitizer", line 11, in <module>
    sys.exit(main())
  File "/Users/edwin/code/test/venv/lib/python3.6/site-packages/database_sanitizer/__main__.py", line 60, in main
    config=config,
  File "/Users/edwin/code/test/venv/lib/python3.6/site-packages/database_sanitizer/dump/__init__.py", line 46, in run
    for line in db_module.sanitize(url=parsed_url, config=config):
  File "/Users/edwin/code/test/venv/lib/python3.6/site-packages/database_sanitizer/dump/mysql.py", line 68, in sanitize
    stdout=subprocess.PIPE,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mysqldump': 'mysqldump'
```

**Comment by azin634** [comment]
Posting on stackoverflow instead
